# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Generation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Generation.proto\x12\x10image_generation\"\xc5\x01\n\x04Text\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0f\n\x07seedVal\x18\x03 \x01(\x05\x12\x10\n\x08n_images\x18\x04 \x01(\x05\x12\r\n\x05steps\x18\x05 \x01(\x05\x12\x14\n\x0cprompt_style\x18\x06 \x01(\t\x12\r\n\x05image\x18\x07 \x01(\x0c\x12\x17\n\x0fnegative_prompt\x18\x08 \x01(\t\x12\t\n\x01H\x18\t \x01(\x05\x12\t\n\x01W\x18\n \x01(\x05\x12\x16\n\x0eguidance_scale\x18\x0b \x01(\x01\"\x17\n\x05Image\x12\x0e\n\x06image1\x18\x01 \x01(\t2L\n\x10image_generation\x12\x38\n\x03Gen\x12\x16.image_generation.Text\x1a\x17.image_generation.Image\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Generation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXT._serialized_start=39
  _TEXT._serialized_end=236
  _IMAGE._serialized_start=238
  _IMAGE._serialized_end=261
  _IMAGE_GENERATION._serialized_start=263
  _IMAGE_GENERATION._serialized_end=339
# @@protoc_insertion_point(module_scope)
